[package]
name = "tm4c129x"
version = "0.1.0"
authors = ["Alexander Müllner <es16m017@technikum-wien.at>"]

[dependencies]
cortexm4 = { git = "https://github.com/tock/tock", tag = "release-1.3" }
kernel = { git = "https://github.com/tock/tock", tag = "release-1.3" }
